USE [master]
GO

/****** Object:  Database [CQRSinPractice]    Script Date: 12/07/2019 21:53:38 ******/
CREATE DATABASE [CQRSinPractice]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CQRSinPractice', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER17\MSSQL\DATA\CQRSinPractice.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CQRSinPractice_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER17\MSSQL\DATA\CQRSinPractice_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CQRSinPractice] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CQRSinPractice].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CQRSinPractice] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CQRSinPractice] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CQRSinPractice] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CQRSinPractice] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CQRSinPractice] SET ARITHABORT OFF 
GO

ALTER DATABASE [CQRSinPractice] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CQRSinPractice] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CQRSinPractice] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CQRSinPractice] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CQRSinPractice] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CQRSinPractice] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CQRSinPractice] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CQRSinPractice] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CQRSinPractice] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CQRSinPractice] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CQRSinPractice] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CQRSinPractice] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CQRSinPractice] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CQRSinPractice] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CQRSinPractice] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CQRSinPractice] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CQRSinPractice] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CQRSinPractice] SET RECOVERY FULL 
GO

ALTER DATABASE [CQRSinPractice] SET  MULTI_USER 
GO

ALTER DATABASE [CQRSinPractice] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CQRSinPractice] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CQRSinPractice] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CQRSinPractice] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CQRSinPractice] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CQRSinPractice] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CQRSinPractice] SET  READ_WRITE 
GO


